# Dependabot configuration:
# https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  # Maintain dependencies for .NET dependencies
  - package-ecosystem: "nuget"
    directory: "/"
    target-branch: "develop"
    schedule:
      interval: "daily"
    groups:
      dev-dependencies:
        patterns:
          - "*"
  # Maintain dependencies for Docker dependencies
  - package-ecosystem: "docker"
    directory: "/StarWarsProgressBarIssueTracker.App"
    target-branch: "develop"
    schedule:
      interval: "daily"
    groups:
      dev-dependencies:
        patterns:
          - "*"
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "develop"
    schedule:
      interval: "daily"
    groups:
      dev-dependencies:
        patterns:
          - "*"
