using StarWarsProgressBarIssueTracker.Domain.Configuration;

namespace StarWarsProgressBarIssueTracker.Infrastructure.Gitlab.Configuration;

public class GitlabConfiguration : IssuesConnectionConfig;
