using StarWarsProgressBarIssueTracker.Domain.Configuration;

namespace StarWarsProgressBarIssueTracker.Infrastructure.GitHub.Configuration;

public class GitHubConfiguration : IssuesConnectionConfig;
