# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  HUSKY: 0

jobs:
  appTests:
    name: App tests

    runs-on: ubuntu-latest

    needs: [build]

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.x

    - name: Restore dependencies
      run: dotnet restore StarWarsProgressBarIssueTracker.App.Tests/StarWarsProgressBarIssueTracker.App.Tests.csproj

    - name: Build
      run: dotnet build StarWarsProgressBarIssueTracker.App.Tests/StarWarsProgressBarIssueTracker.App.Tests.csproj --no-restore

    - name: Test
      run: |
        dotnet test StarWarsProgressBarIssueTracker.App.Tests/StarWarsProgressBarIssueTracker.App.Tests.csproj --no-build --verbosity q --logger "trx;LogFileName=./.test-results/app-tests.trx" 2>&1 | tee test_output.txt
        if [[ ${PIPESTATUS[0]} -ne 0 ]]; then
          exit 1
        fi

    - name: Upload test_output.txt for debugging
      if: steps.run-tests.outcome == 'failure'
      uses: actions/upload-artifact@v2
      with:
        name: test-output
        path: test_output.txt
