name: update-dotnet-sdk

on:
  schedule:
    - cron:  '00 20 * * TUE'
  workflow_dispatch:

jobs:
  update-dotnet-sdk:
    name: Update .NET SDK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: 'dev' # Checkout the dev branch instead of the default branch
      - uses: martincostello/update-dotnet-sdk@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
